### PR TITLE
Make generation of the *_GIT_SHA1 variables optional

### PR DESCRIPTION
**Pull request by wsmigaj**
For projects in Git repositories, ecbuild generates variables recording the hash of the git revision at the time of the last build. This is no doubt useful in production, but it is awkward during development, since it causes CMake to be re-run after each Git commit, which can be time-consuming for large projects. This PR adds an option to disable generation of these variables.

As things stand, this option is not marked as advanced, but I'm happy to mark it as such.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf/ecbuild?pullRequest=21) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/ecbuild?pullRequest=21) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/ecbuild?pullRequest=21) it.</sub>

**Comment by wsmigaj** [comment]
Many thanks for the review. I will mark the option as advanced. I can also rename it, but the proposed name would clash with the name of the variable storing the full Git revision for an ecbuild project called ``RECORD_SOURCE``. Do you think it is sufficiently unlikely that someone will create a project with that name?

**Comment by oiffrig** [comment]
Good point. Maybe ``RECORD_GIT_COMMIT_SHA1`` then?

**Comment by wdeconinck** [comment]
How about `ECBUILD_RECORD_GIT_COMMIT_SHA1` ?

**Comment by wsmigaj** [comment]
OK, I've renamed the option to ``ECBUILD_RECORD_GIT_COMMIT_SHA1`` and marked it as advanced.

**Pull request merged**
